version: "3.9"

services: 
  salt-master:
    image: salt:latest
    tty: true
    volumes:
      - salt-etc:/etc/salt
      - salt-opt:/opt/salt
    restart: always
    ports:
      - 4505:4505
      - 4506:4506

volumes:
 salt-etc: {}
 salt-opt: {}
 salt-logs: {}
